# Generated by Django 6.0.1 on 2026-01-09 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                upload_to="videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "mov",
                            "avi",
                            "mkv",
                            "webm",
                            "flv",
                            "wmv",
                        ]
                    )
                ],
            ),
        ),
    ]
