# Generated by Django 6.0.1 on 2026-01-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
    ]
