# Generated by Django 6.0.1 on 2026-01-14 05:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_video_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                upload_to="videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "mov",
                            "avi",
                            "mkv",
                            "webm",
                            "flv",
                            "wmv",
                            "m4v",
                        ]
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="TranscriptChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_id", models.IntegerField()),
                ("text", models.TextField()),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "ordering": ["video", "chunk_id"],
                "unique_together": {("video", "chunk_id")},
            },
        ),
    ]
