# Generated by Django 6.0.1 on 2026-01-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_alter_video_file_transcriptchunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptchunk",
            name="segments",
            field=models.JSONField(default=list),
        ),
    ]
