# Generated by Django 6.0.1 on 2026-01-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_transcriptchunk_segments"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
