# Generated by Django 6.0.1 on 2026-01-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_video_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="progress",
        ),
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
    ]
