# Generated by Django 6.0.1 on 2026-01-26 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_remove_video_progress_alter_video_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "mov",
                            "avi",
                            "mkv",
                            "webm",
                            "flv",
                            "wmv",
                            "m4v",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("downloading", "Downloading"),
                    ("transcribing", "Transcribing"),
                    ("chunking", "Chunking"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
    ]
