# Generated by Django 6.0.1 on 2026-01-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0008_video_error_message_video_youtube_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptchunk",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
