# Generated by Django 6.0.1 on 2026-01-28 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0009_transcriptchunk_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.FloatField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="frames/"),
                ),
                ("visual_context", models.TextField()),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "ordering": ["video", "timestamp"],
            },
        ),
    ]
