# Generated by Django 6.0.1 on 2026-01-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0010_videoframe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("downloading", "Downloading"),
                    ("transcribing", "Transcribing"),
                    ("chunking", "Chunking"),
                    ("scanning", "Scanning"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
    ]
