# Generated by Django 6.0.1 on 2026-01-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0011_alter_video_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="processing_mode",
            field=models.CharField(
                choices=[
                    ("audio", "Audio Only"),
                    ("visual", "Visual Only"),
                    ("both", "Audio + Visual"),
                ],
                default="both",
                max_length=20,
            ),
        ),
    ]
