# Generated by Django 6.0.1 on 2026-01-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0014_video_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoframe",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
